### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by Kief5555** [hellotojello/FakeLockScreen#1]
Hi,

2 quick questions.

1. Is this going to work on big sur (mac)
2. Can you please make a download if it does?

**Comment by alvintu** [comment]
Hey,
That project was made 5 years ago in objective-c and only works on iPhones.

If you go to this link <https://github.com/ajtu/FakeLockScreen> , you can
click Code >> Download ZIP, and be able to run the app on Xcode.

Thanks,
Alvin

**Comment by alvintu** [comment]
I'm closing this issue. Feel free to ask questions in the future. @Kief5555

**Comment by Kief5555** [comment]
Ok thanks!
